# Turn vector csv into npy

In [1]:
# Basic import
import os
import sys
import json
import shutil
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Helper function
def writeProgress(msg, count, total):
    sys.stdout.write(msg + "{:.2%}\r".format(count/total))
    sys.stdout.flush()
    
def newPath(path):
    if not os.path.isdir(path):
        os.mkdir(path)

def read_json(src_path):
    with open(src_path, 'r') as json_file:
        data = json.load(json_file)
    return data

def write_json(data,dst_path):
    with open(dst_path, 'w') as outfile:
        json.dump(data, outfile)

def writeLog(row):
    with open('log.txt', 'a') as outfile:
        outfile.write(row + '\n')

def getErrMsg(e):
    error_class = e.__class__.__name__ #取得錯誤類型
    detail = e.args[0] #取得詳細內容
    errMsg = "[{}] {}".format(error_class, detail)
    return errMsg

# Feature

## Text

In [3]:
PATH = '../Text/output/TextFeatureVec.csv'
SAVE_NAME = 'text'

In [4]:
df = pd.read_csv(PATH, header = None)
df

0         1         2         3         4         5    \
0        21bridgesmovie  4.625625  0.270240  0.843757  0.361738  0.385804   
1          47metersdown  1.227327  1.386205  1.245207  0.483765  1.854537   
2    abeautifuldaymovie  0.302373  0.038617  0.328554  0.393081  0.214754   
3       abominablemovie  0.186162  0.000000  0.089363  0.246190  0.235176   
4          adastramovie  3.830110  1.397172  1.287266  0.298948  1.933444   
..                  ...       ...       ...       ...       ...       ...   
160    wrinklestheclown  0.853294  0.896881  0.000000  1.337605  1.505762   
161          xmenmovies  2.842772  0.806930  5.102901  0.388758  1.401573   
162          yardiefilm  2.580427  0.371021  0.258102  1.061416  0.314597   
163      yesterdaymovie  1.098065  1.916392  0.428723  0.717684  1.611092   
164          zombieland  4.156315  2.123129  3.339168  1.519991  2.271654   

          6         7         8         9    ...       291       292  \
0    0.386609  1.417814  3.703098  1.964221  ...  0.518959  1.518856   
1    1.861350  1.422121  1.313766  1.073333  ...  2.369604  0.415461   
2    0.233469  0.234261  0.317635  2.241514  ...  1.382313  0.505444   
3    0.256702  0.428070  0.513695  0.565004  ...  0.586406  0.315049   
4    2.106336  2.286842  2.996085  1.740809  ...  1.833267  1.069029   
..        ...       ...       ...       ...  ...       ...       ...   
160  1.014642  0.112749  0.271832  0.412343  ...  1.331714  1.854079   
161  1.073662  4.430752  5.804434  0.536433  ...  0.906498  0.570307   
162  0.228967  0.332296  2.102141  2.003907  ...  1.032518  2.002433   
163  1.348285  0.459656  0.504291  0.889729  ...  3.017361  1.263357   
164  1.795395  3.109476  4.125190  0.895719  ...  1.640270  2.695757   

          293       294       295       296       297       298       299  \
0    1.617028  0.689357  0.253527  0.424694  3.344936  3.522084  0.689225   
1    2.303477  1.855965  0.722303  0.954403  1.338140  0.958282  1.601425   
2    0.411402  1.813654  0.109178  0.619214  4.462339  0.545749  0.698804   
3    0.432583  1.190027  0.128935  0.620930  0.421282  0.109546  0.694254   
4    3.520368  0.546656  1.459306  0.568826  2.526160  2.906972  1.745568   
..        ...       ...       ...       ...       ...       ...       ...   
160  0.000000  1.670097  0.958906  0.974099  0.554800  0.130257  0.475131   
161  9.188423  1.268965  0.614569  2.790452  1.126672  3.803742  7.926337   
162  0.319524  1.297553  0.279873  1.396268  3.653067  2.020441  0.691687   
163  0.501066  1.724245  1.742528  0.652188  1.596182  0.407870  0.948900   
164  6.212105  0.800507  2.376627  1.591925  1.297943  2.721867  5.013988   

          300  
0    2.659301  
1    1.273016  
2    2.974110  
3    0.206418  
4    2.181656  
..        ...  
160  0.115792  
161  0.756108  
162  2.927576  
163  0.851927  
164  0.995655  

[165 rows x 301 columns]

In [5]:
df = df.loc[:, 1:]
df

1         2         3         4         5         6         7    \
0    4.625625  0.270240  0.843757  0.361738  0.385804  0.386609  1.417814   
1    1.227327  1.386205  1.245207  0.483765  1.854537  1.861350  1.422121   
2    0.302373  0.038617  0.328554  0.393081  0.214754  0.233469  0.234261   
3    0.186162  0.000000  0.089363  0.246190  0.235176  0.256702  0.428070   
4    3.830110  1.397172  1.287266  0.298948  1.933444  2.106336  2.286842   
..        ...       ...       ...       ...       ...       ...       ...   
160  0.853294  0.896881  0.000000  1.337605  1.505762  1.014642  0.112749   
161  2.842772  0.806930  5.102901  0.388758  1.401573  1.073662  4.430752   
162  2.580427  0.371021  0.258102  1.061416  0.314597  0.228967  0.332296   
163  1.098065  1.916392  0.428723  0.717684  1.611092  1.348285  0.459656   
164  4.156315  2.123129  3.339168  1.519991  2.271654  1.795395  3.109476   

          8         9         10   ...       291       292       293  \
0    3.703098  1.964221  0.340831  ...  0.518959  1.518856  1.617028   
1    1.313766  1.073333  1.669586  ...  2.369604  0.415461  2.303477   
2    0.317635  2.241514  0.386934  ...  1.382313  0.505444  0.411402   
3    0.513695  0.565004  0.521737  ...  0.586406  0.315049  0.432583   
4    2.996085  1.740809  1.958116  ...  1.833267  1.069029  3.520368   
..        ...       ...       ...  ...       ...       ...       ...   
160  0.271832  0.412343  0.873156  ...  1.331714  1.854079  0.000000   
161  5.804434  0.536433  0.629329  ...  0.906498  0.570307  9.188423   
162  2.102141  2.003907  0.501374  ...  1.032518  2.002433  0.319524   
163  0.504291  0.889729  2.496572  ...  3.017361  1.263357  0.501066   
164  4.125190  0.895719  1.967186  ...  1.640270  2.695757  6.212105   

          294       295       296       297       298       299       300  
0    0.689357  0.253527  0.424694  3.344936  3.522084  0.689225  2.659301  
1    1.855965  0.722303  0.954403  1.338140  0.958282  1.601425  1.273016  
2    1.813654  0.109178  0.619214  4.462339  0.545749  0.698804  2.974110  
3    1.190027  0.128935  0.620930  0.421282  0.109546  0.694254  0.206418  
4    0.546656  1.459306  0.568826  2.526160  2.906972  1.745568  2.181656  
..        ...       ...       ...       ...       ...       ...       ...  
160  1.670097  0.958906  0.974099  0.554800  0.130257  0.475131  0.115792  
161  1.268965  0.614569  2.790452  1.126672  3.803742  7.926337  0.756108  
162  1.297553  0.279873  1.396268  3.653067  2.020441  0.691687  2.927576  
163  1.724245  1.742528  0.652188  1.596182  0.407870  0.948900  0.851927  
164  0.800507  2.376627  1.591925  1.297943  2.721867  5.013988  0.995655  

[165 rows x 300 columns]

In [6]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 300) [[4.625625   0.27023974 0.8437569  ... 3.5220842  0.6892248  2.659301  ]
 [1.2273268  1.3862046  1.245207   ... 0.95828235 1.6014247  1.2730157 ]
 [0.30237263 0.03861726 0.32855368 ... 0.5457492  0.6988041  2.9741096 ]
 ...
 [2.5804267  0.37102053 0.25810206 ... 2.020441   0.69168675 2.9275765 ]
 [1.0980647  1.916392   0.42872304 ... 0.40786976 0.9488999  0.85192657]
 [4.156315   2.1231294  3.3391676  ... 2.7218666  5.0139885  0.99565506]]


In [7]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Image

### Poster

In [3]:
PATH = '../Image/Sample/output/PosterFeatureVec.csv'
SAVE_NAME = 'poster'

In [4]:
df = pd.read_csv(PATH, header = None)
df

0         1         2         3         4         5     \
0        21bridgesmovie.jpg  0.494758  0.283308  0.065662  0.000000  0.335951   
1          47metersdown.jpg  1.519427  0.806621  0.126966  0.261728  0.000000   
2    abeautifuldaymovie.jpg  0.077306  0.613698  0.102838  0.396761  0.265735   
3       abominablemovie.jpg  0.069226  0.056583  0.371933  0.749337  0.059648   
4          adastramovie.jpg  0.729522  0.164893  0.260869  0.015868  0.100866   
..                      ...       ...       ...       ...       ...       ...   
160    wrinklestheclown.jpg  0.199897  0.671948  0.000000  0.019108  0.279197   
161          xmenmovies.jpg  3.063733  1.313999  0.694954  0.000000  0.115780   
162          yardiefilm.jpg  0.587885  0.451792  0.024987  0.018251  1.819033   
163      yesterdaymovie.jpg  0.027935  0.425899  0.004879  0.141607  1.314379   
164          zombieland.jpg  0.802443  0.266962  1.947216  0.000845  0.674209   

         6         7         8         9     ...      2039      2040  \
0    0.031979  0.301165  2.045833  0.208562  ...  0.000000  0.000000   
1    0.108213  0.196652  0.459518  0.259999  ...  0.000000  0.460017   
2    0.039994  0.629388  2.077992  0.590141  ...  0.274793  1.088040   
3    0.569080  0.043452  0.031216  0.071888  ...  0.026392  0.000000   
4    0.313320  0.070898  0.394072  0.166367  ...  0.021538  0.587754   
..        ...       ...       ...       ...  ...       ...       ...   
160  0.039664  0.235553  0.322959  0.146369  ...  0.146693  0.415582   
161  0.000000  0.537104  0.685775  0.888244  ...  0.058512  0.557968   
162  0.144624  0.173273  0.414593  0.040721  ...  0.287570  0.136541   
163  0.013914  0.053892  0.488039  0.114076  ...  0.449295  0.055668   
164  0.034047  0.146127  0.641236  0.057742  ...  0.000000  0.044277   

         2041      2042      2043      2044      2045      2046      2047  \
0    1.193770  1.506646  0.315323  0.583171  0.002632  0.087382  0.069765   
1    1.057664  0.163948  0.223188  0.069748  0.103279  2.986067  0.276734   
2    0.124551  0.122737  0.225596  0.015422  0.000000  0.436052  0.676374   
3    0.000000  0.038951  1.083343  0.126524  0.093844  0.000000  0.523096   
4    0.927968  0.098810  0.000000  0.084116  0.711746  0.378344  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
160  0.784930  0.020980  0.000000  0.000000  0.190380  0.088201  0.000000   
161  0.620168  0.021954  0.758886  1.129855  0.037468  0.134155  0.137868   
162  3.389530  2.044187  0.060037  0.392755  0.274924  0.243140  0.000000   
163  0.644438  0.973870  0.615937  0.005609  0.004708  0.195625  0.029894   
164  0.059140  1.136499  0.740328  0.181827  0.194591  0.105939  0.632977   

         2048  
0    0.469502  
1    0.512829  
2    0.143547  
3    0.034955  
4    0.066408  
..        ...  
160  0.554774  
161  2.214420  
162  0.056881  
163  0.459155  
164  0.018494  

[165 rows x 2049 columns]

In [5]:
df = df.loc[:, 1:]
df

1         2         3         4         5         6         7     \
0    0.494758  0.283308  0.065662  0.000000  0.335951  0.031979  0.301165   
1    1.519427  0.806621  0.126966  0.261728  0.000000  0.108213  0.196652   
2    0.077306  0.613698  0.102838  0.396761  0.265735  0.039994  0.629388   
3    0.069226  0.056583  0.371933  0.749337  0.059648  0.569080  0.043452   
4    0.729522  0.164893  0.260869  0.015868  0.100866  0.313320  0.070898   
..        ...       ...       ...       ...       ...       ...       ...   
160  0.199897  0.671948  0.000000  0.019108  0.279197  0.039664  0.235553   
161  3.063733  1.313999  0.694954  0.000000  0.115780  0.000000  0.537104   
162  0.587885  0.451792  0.024987  0.018251  1.819033  0.144624  0.173273   
163  0.027935  0.425899  0.004879  0.141607  1.314379  0.013914  0.053892   
164  0.802443  0.266962  1.947216  0.000845  0.674209  0.034047  0.146127   

         8         9         10    ...      2039      2040      2041  \
0    2.045833  0.208562  0.941920  ...  0.000000  0.000000  1.193770   
1    0.459518  0.259999  1.053462  ...  0.000000  0.460017  1.057664   
2    2.077992  0.590141  0.050286  ...  0.274793  1.088040  0.124551   
3    0.031216  0.071888  0.186235  ...  0.026392  0.000000  0.000000   
4    0.394072  0.166367  0.147495  ...  0.021538  0.587754  0.927968   
..        ...       ...       ...  ...       ...       ...       ...   
160  0.322959  0.146369  1.392606  ...  0.146693  0.415582  0.784930   
161  0.685775  0.888244  0.266433  ...  0.058512  0.557968  0.620168   
162  0.414593  0.040721  0.121475  ...  0.287570  0.136541  3.389530   
163  0.488039  0.114076  0.150991  ...  0.449295  0.055668  0.644438   
164  0.641236  0.057742  0.345229  ...  0.000000  0.044277  0.059140   

         2042      2043      2044      2045      2046      2047      2048  
0    1.506646  0.315323  0.583171  0.002632  0.087382  0.069765  0.469502  
1    0.163948  0.223188  0.069748  0.103279  2.986067  0.276734  0.512829  
2    0.122737  0.225596  0.015422  0.000000  0.436052  0.676374  0.143547  
3    0.038951  1.083343  0.126524  0.093844  0.000000  0.523096  0.034955  
4    0.098810  0.000000  0.084116  0.711746  0.378344  0.000000  0.066408  
..        ...       ...       ...       ...       ...       ...       ...  
160  0.020980  0.000000  0.000000  0.190380  0.088201  0.000000  0.554774  
161  0.021954  0.758886  1.129855  0.037468  0.134155  0.137868  2.214420  
162  2.044187  0.060037  0.392755  0.274924  0.243140  0.000000  0.056881  
163  0.973870  0.615937  0.005609  0.004708  0.195625  0.029894  0.459155  
164  1.136499  0.740328  0.181827  0.194591  0.105939  0.632977  0.018494  

[165 rows x 2048 columns]

In [6]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 2048) [[0.49475807 0.28330824 0.06566165 ... 0.08738196 0.06976548 0.469502  ]
 [1.5194275  0.80662096 0.12696646 ... 2.9860668  0.2767335  0.512829  ]
 [0.07730576 0.6136975  0.10283829 ... 0.43605196 0.6763744  0.14354736]
 ...
 [0.5878847  0.45179185 0.02498718 ... 0.2431399  0.         0.05688086]
 [0.02793477 0.42589915 0.0048787  ... 0.19562516 0.02989419 0.45915523]
 [0.8024434  0.26696184 1.9472163  ... 0.10593923 0.6329765  0.01849403]]


In [7]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

### IG

In [8]:
PATH = '../Image/Sample/output/IGimgFeatureVec.csv'
SAVE_NAME = 'IGimg'

In [9]:
df = pd.read_csv(PATH, header = None)
df

0         1         2         3         4     \
0      21bridgesmovie_22217.jpg  0.331813  0.334793  0.020973  0.069121   
1      21bridgesmovie_22218.jpg  0.130291  1.547714  0.000000  0.073273   
2      21bridgesmovie_22219.jpg  0.740051  0.824680  0.251876  0.419343   
3      21bridgesmovie_22220.jpg  0.025813  0.771999  0.054810  0.051743   
4      21bridgesmovie_22221.jpg  0.090466  0.000000  0.128749  0.238021   
...                         ...       ...       ...       ...       ...   
37954       zombieland_7839.jpg  0.088361  0.302754  0.001350  0.164013   
37955       zombieland_7840.jpg  0.182120  0.010173  0.311166  0.024346   
37956       zombieland_7841.jpg  0.040291  0.915755  0.070129  0.016132   
37957       zombieland_7842.jpg  0.048829  0.411975  0.000000  0.000000   
37958       zombieland_7843.jpg  0.161385  0.521045  1.093487  0.549951   

           5         6         7         8         9     ...      2039  \
0      1.450596  0.712886  0.480257  2.208983  0.162940  ...  0.056089   
1      0.078071  0.000000  0.070401  0.289346  1.153553  ...  0.249781   
2      1.076743  0.000000  0.213411  1.576596  0.005514  ...  0.058990   
3      0.039484  0.000000  0.156691  0.859746  0.019721  ...  0.000000   
4      0.595631  0.050999  0.455349  1.931511  0.207198  ...  0.134479   
...         ...       ...       ...       ...       ...  ...       ...   
37954  0.895509  0.000000  0.053063  0.329108  0.000000  ...  0.164409   
37955  1.038138  0.094662  0.041859  0.491167  0.170245  ...  0.000000   
37956  0.109926  0.310837  0.000000  0.000000  0.476589  ...  0.000000   
37957  1.094483  0.074808  0.178307  0.607130  0.002279  ...  0.000000   
37958  2.184265  1.169457  0.033490  0.336400  0.232571  ...  0.333437   

           2040      2041      2042      2043      2044      2045      2046  \
0      0.797267  2.800650  3.000357  1.523949  0.498544  0.071483  0.768686   
1      0.349757  2.192273  0.376216  0.488646  0.094902  0.612856  1.569600   
2      0.071405  2.646841  1.244074  0.219941  0.082223  0.207473  0.020224   
3      0.445953  1.831583  0.183303  0.152106  0.255341  1.063585  1.252706   
4      0.945805  0.132786  0.873131  0.120998  0.000000  0.002045  0.448773   
...         ...       ...       ...       ...       ...       ...       ...   
37954  0.034488  0.118139  1.469632  0.608908  0.141757  0.040633  0.111562   
37955  0.154903  0.068876  1.120993  0.730786  0.363519  0.074791  0.096592   
37956  0.076708  0.338057  0.531682  0.128355  0.000000  0.002735  1.048143   
37957  0.132978  0.405171  1.677894  0.123480  0.112938  0.000000  0.083492   
37958  0.124930  0.005909  0.558952  1.602938  0.012159  0.064567  0.308352   

           2047      2048  
0      0.021901  0.038476  
1      0.080053  0.332811  
2      0.100037  0.711623  
3      0.332302  0.199079  
4      0.229544  0.125882  
...         ...       ...  
37954  0.066248  0.667725  
37955  0.128792  0.585530  
37956  0.076546  0.056163  
37957  0.043363  0.289784  
37958  0.669774  0.769733  

[37959 rows x 2049 columns]

In [10]:
df['username'] = [string.split('_')[0] for string in df[0]]
df

0         1         2         3         4  \
0      21bridgesmovie_22217.jpg  0.331813  0.334793  0.020973  0.069121   
1      21bridgesmovie_22218.jpg  0.130291  1.547714  0.000000  0.073273   
2      21bridgesmovie_22219.jpg  0.740051  0.824680  0.251876  0.419343   
3      21bridgesmovie_22220.jpg  0.025813  0.771999  0.054810  0.051743   
4      21bridgesmovie_22221.jpg  0.090466  0.000000  0.128749  0.238021   
...                         ...       ...       ...       ...       ...   
37954       zombieland_7839.jpg  0.088361  0.302754  0.001350  0.164013   
37955       zombieland_7840.jpg  0.182120  0.010173  0.311166  0.024346   
37956       zombieland_7841.jpg  0.040291  0.915755  0.070129  0.016132   
37957       zombieland_7842.jpg  0.048829  0.411975  0.000000  0.000000   
37958       zombieland_7843.jpg  0.161385  0.521045  1.093487  0.549951   

              5         6         7         8         9  ...      2040  \
0      1.450596  0.712886  0.480257  2.208983  0.162940  ...  0.797267   
1      0.078071  0.000000  0.070401  0.289346  1.153553  ...  0.349757   
2      1.076743  0.000000  0.213411  1.576596  0.005514  ...  0.071405   
3      0.039484  0.000000  0.156691  0.859746  0.019721  ...  0.445953   
4      0.595631  0.050999  0.455349  1.931511  0.207198  ...  0.945805   
...         ...       ...       ...       ...       ...  ...       ...   
37954  0.895509  0.000000  0.053063  0.329108  0.000000  ...  0.034488   
37955  1.038138  0.094662  0.041859  0.491167  0.170245  ...  0.154903   
37956  0.109926  0.310837  0.000000  0.000000  0.476589  ...  0.076708   
37957  1.094483  0.074808  0.178307  0.607130  0.002279  ...  0.132978   
37958  2.184265  1.169457  0.033490  0.336400  0.232571  ...  0.124930   

           2041      2042      2043      2044      2045      2046      2047  \
0      2.800650  3.000357  1.523949  0.498544  0.071483  0.768686  0.021901   
1      2.192273  0.376216  0.488646  0.094902  0.612856  1.569600  0.080053   
2      2.646841  1.244074  0.219941  0.082223  0.207473  0.020224  0.100037   
3      1.831583  0.183303  0.152106  0.255341  1.063585  1.252706  0.332302   
4      0.132786  0.873131  0.120998  0.000000  0.002045  0.448773  0.229544   
...         ...       ...       ...       ...       ...       ...       ...   
37954  0.118139  1.469632  0.608908  0.141757  0.040633  0.111562  0.066248   
37955  0.068876  1.120993  0.730786  0.363519  0.074791  0.096592  0.128792   
37956  0.338057  0.531682  0.128355  0.000000  0.002735  1.048143  0.076546   
37957  0.405171  1.677894  0.123480  0.112938  0.000000  0.083492  0.043363   
37958  0.005909  0.558952  1.602938  0.012159  0.064567  0.308352  0.669774   

           2048        username  
0      0.038476  21bridgesmovie  
1      0.332811  21bridgesmovie  
2      0.711623  21bridgesmovie  
3      0.199079  21bridgesmovie  
4      0.125882  21bridgesmovie  
...         ...             ...  
37954  0.667725      zombieland  
37955  0.585530      zombieland  
37956  0.056163      zombieland  
37957  0.289784      zombieland  
37958  0.769733      zombieland  

[37959 rows x 2050 columns]

In [11]:
group = df.groupby('username').mean()
group.to_csv('../Image/Sample/output/IGimgFeatureVec_group.csv')
group

1         2         3         4         5     \
username                                                               
21bridgesmovie      0.493511  0.456718  0.159513  0.139757  0.733778   
47metersdown        0.959267  0.450579  0.138192  0.221089  0.196270   
abeautifuldaymovie  0.216008  0.665498  0.140317  0.519259  0.331685   
abominablemovie     0.321312  0.249236  0.156039  0.842645  0.451429   
adastramovie        0.535617  0.354574  0.336503  0.142333  0.413927   
...                      ...       ...       ...       ...       ...   
wrinklestheclown    0.420413  0.905093  0.059553  0.353043  0.186951   
xmenmovies          0.533515  0.527889  0.380976  0.224500  0.256823   
yardiefilm          0.570591  0.523850  0.269837  0.205206  0.609369   
yesterdaymovie      0.241110  0.268485  0.169761  0.152681  0.862261   
zombieland          0.319944  0.316458  0.212092  0.187379  0.737168   

                        6         7         8         9         10    ...  \
username                                                              ...   
21bridgesmovie      0.283911  0.178954  1.588011  0.426711  0.131176  ...   
47metersdown        0.175800  0.284615  0.359620  0.072881  0.403770  ...   
abeautifuldaymovie  0.123064  0.967564  1.409957  0.271901  0.356101  ...   
abominablemovie     0.310091  0.111814  0.109763  0.198508  0.180987  ...   
adastramovie        0.300933  0.239407  0.477948  0.205328  0.298817  ...   
...                      ...       ...       ...       ...       ...  ...   
wrinklestheclown    0.281562  0.151260  0.087675  0.135054  0.647792  ...   
xmenmovies          0.074202  0.335687  0.862431  0.354468  0.684171  ...   
yardiefilm          0.265700  0.276377  0.705793  0.134432  0.218250  ...   
yesterdaymovie      0.161442  0.633406  0.235377  0.210424  0.148196  ...   
zombieland          0.163008  0.164325  0.324855  0.234254  0.281722  ...   

                        2039      2040      2041      2042      2043  \
username                                                               
21bridgesmovie      0.163705  0.445806  2.073926  1.778595  0.391657   
47metersdown        0.193652  0.575036  0.692117  0.278784  0.220668   
abeautifuldaymovie  0.629256  0.614837  0.822323  0.851326  0.318444   
abominablemovie     0.237197  0.197429  0.120572  0.199731  0.641133   
adastramovie        0.268620  1.134822  0.802182  0.431821  0.398653   
...                      ...       ...       ...       ...       ...   
wrinklestheclown    0.172867  0.345677  0.333366  0.122942  0.110897   
xmenmovies          0.388859  0.528630  0.783260  0.637888  0.442711   
yardiefilm          0.312322  0.257836  1.068061  1.087042  0.238596   
yesterdaymovie      0.659321  0.155542  0.224081  0.437979  0.242450   
zombieland          0.338249  0.314066  0.371568  0.758299  0.392903   

                        2044      2045      2046      2047      2048  
username                                                              
21bridgesmovie      0.208094  0.311020  0.656493  0.252922  0.261573  
47metersdown        0.112783  0.182530  1.061706  0.228888  0.327805  
abeautifuldaymovie  0.025505  0.109678  0.762225  0.390723  0.397177  
abominablemovie     0.063515  0.170164  0.213464  0.450424  0.173634  
adastramovie        0.080874  0.148955  0.913962  0.400167  0.327246  
...                      ...       ...       ...       ...       ...  
wrinklestheclown    0.059047  0.427274  0.275375  0.103697  0.238406  
xmenmovies          0.156306  0.227469  0.321024  0.789155  0.341580  
yardiefilm          0.100592  0.172321  0.510214  0.343606  0.232004  
yesterdaymovie      0.044548  0.099211  0.245290  0.265239  0.665381  
zombieland          0.109446  0.094622  0.448191  0.247054  0.298940  

[165 rows x 2048 columns]

In [12]:
npy = group.to_numpy()
print(npy.shape, npy)

(165, 2048) [[0.4935109  0.45671789 0.15951251 ... 0.65649261 0.25292226 0.26157303]
 [0.95926712 0.45057878 0.13819194 ... 1.06170623 0.22888842 0.32780538]
 [0.21600796 0.66549798 0.14031741 ... 0.7622245  0.39072257 0.39717658]
 ...
 [0.57059085 0.52384985 0.26983693 ... 0.51021401 0.34360608 0.23200411]
 [0.2411104  0.26848473 0.16976135 ... 0.24529025 0.265239   0.66538086]
 [0.31994406 0.31645807 0.21209246 ... 0.44819088 0.24705376 0.2989397 ]]


In [13]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Video

In [8]:
PATH = '../Video/csv/computed_minmaxnorm_2019_log.csv'
SAVE_NAME = 'video'

In [10]:
df = pd.read_csv(PATH)
df

Movie     A_avg     A_std      B_avg      B_std     C_avg  \
0        21bridgesmovie  3.518647  3.413387  13.907436  15.439361  0.186758   
1          47metersdown  3.549758  3.171456  16.295219  17.237230  0.245609   
2    abeautifuldaymovie  3.743390  3.729937  14.801673  15.869060  0.237930   
3       abominablemovie  3.487348  3.274070  17.482964  18.210801  0.251836   
4          adastramovie  4.081181  4.021839  13.771053  14.892246  0.253118   
..                  ...       ...       ...        ...        ...       ...   
160    wrinklestheclown  3.674363  3.291100  16.343698  17.367981  0.218662   
161          xmenmovies  3.726881  3.525028  15.382260  16.515194  0.319549   
162          yardiefilm  3.705499  3.711716  13.653330  14.709328  0.176796   
163      yesterdaymovie  3.462233  3.155266  16.416116  17.207047  0.180151   
164          zombieland  3.620412  3.433065  16.049908  16.704344  0.287000   

        C_std     D_avg     D_std  A_avg_minmaxnorm  A_std_minmaxnorm  \
0    0.245622  7.270932  7.083156          0.064317          0.212065   
1    0.249743  8.251181  8.097400          0.073366          0.153932   
2    0.307260  8.239522  7.781294          0.129683          0.288129   
3    0.284515  8.498778  7.970775          0.055214          0.178589   
4    0.300952  8.075115  7.784539          0.227927          0.358270   
..        ...       ...       ...               ...               ...   
160  0.281909  8.255468  8.273745          0.109606          0.182681   
161  0.279627  7.990810  7.741344          0.124881          0.238892   
162  0.197451  7.693021  7.423313          0.118662          0.283751   
163  0.253020  8.418139  8.124500          0.047910          0.150041   
164  0.305738  8.530966  8.010033          0.093915          0.216794   

     B_avg_minmaxnorm  B_std_minmaxnorm  C_avg_minmaxnorm  C_std_minmaxnorm  \
0            0.425476          0.512305          0.303963          0.455250   
1            0.661132          0.679877          0.471069          0.471811   
2            0.513731          0.552355          0.449266          0.702974   
3            0.778354          0.770619          0.488753          0.611561   
4            0.412016          0.461310          0.492392          0.677623   
..                ...               ...               ...               ...   
160          0.665917          0.692064          0.394556          0.601089   
161          0.571030          0.612579          0.681022          0.591916   
162          0.400398          0.444261          0.275676          0.261650   
163          0.673064          0.677064          0.285204          0.484984   
164          0.636922          0.630209          0.588598          0.696858   

     D_avg_minmaxnorm  D_std_minmaxnorm  
0            0.029611          0.013163  
1            0.588256          0.853833  
2            0.581612          0.591825  
3            0.729362          0.748879  
4            0.487916          0.594514  
..                ...               ...  
160          0.590700          1.000000  
161          0.439871          0.558712  
162          0.270160          0.295108  
163          0.683406          0.876296  
164          0.747707          0.781419  

[165 rows x 17 columns]

In [12]:
df = df.iloc[:, 9:]
df

A_avg_minmaxnorm  A_std_minmaxnorm  B_avg_minmaxnorm  B_std_minmaxnorm  \
0            0.064317          0.212065          0.425476          0.512305   
1            0.073366          0.153932          0.661132          0.679877   
2            0.129683          0.288129          0.513731          0.552355   
3            0.055214          0.178589          0.778354          0.770619   
4            0.227927          0.358270          0.412016          0.461310   
..                ...               ...               ...               ...   
160          0.109606          0.182681          0.665917          0.692064   
161          0.124881          0.238892          0.571030          0.612579   
162          0.118662          0.283751          0.400398          0.444261   
163          0.047910          0.150041          0.673064          0.677064   
164          0.093915          0.216794          0.636922          0.630209   

     C_avg_minmaxnorm  C_std_minmaxnorm  D_avg_minmaxnorm  D_std_minmaxnorm  
0            0.303963          0.455250          0.029611          0.013163  
1            0.471069          0.471811          0.588256          0.853833  
2            0.449266          0.702974          0.581612          0.591825  
3            0.488753          0.611561          0.729362          0.748879  
4            0.492392          0.677623          0.487916          0.594514  
..                ...               ...               ...               ...  
160          0.394556          0.601089          0.590700          1.000000  
161          0.681022          0.591916          0.439871          0.558712  
162          0.275676          0.261650          0.270160          0.295108  
163          0.285204          0.484984          0.683406          0.876296  
164          0.588598          0.696858          0.747707          0.781419  

[165 rows x 8 columns]

In [13]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 8) [[0.06431727 0.21206534 0.42547612 ... 0.45525045 0.02961095 0.01316341]
 [0.07336566 0.15393189 0.66113249 ... 0.47181116 0.58825642 0.85383342]
 [0.12968256 0.28812912 0.51373062 ... 0.70297361 0.58161191 0.59182537]
 ...
 [0.11866202 0.28375068 0.40039768 ... 0.26164951 0.2701602  0.29510787]
 [0.04790979 0.15004138 0.6730642  ... 0.48498426 0.68340588 0.87629614]
 [0.09391496 0.21679366 0.6369222  ... 0.6968582  0.74770654 0.78141881]]


In [14]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Follow

In [19]:
PATH = '../Autoencoder/input/followingMatrix_over1.csv'
SAVE_NAME = 'follow'

In [20]:
df = pd.read_csv(PATH)
df

movie  20thcenturyfox  a24  accessonline  adamsandler  \
0        21bridgesmovie               0    0             0            0   
1          47metersdown               0    0             0            0   
2    abeautifuldaymovie               0    0             0            0   
3       abominablemovie               0    0             0            0   
4          adastramovie               1    0             0            0   
..                  ...             ...  ...           ...          ...   
160    wrinklestheclown               0    0             0            0   
161          xmenmovies               1    0             0            0   
162          yardiefilm               0    0             0            0   
163      yesterdaymovie               0    0             0            0   
164          zombieland               0    0             0            0   

     adamshankman  agt  aldis_hodge  alecbaldwininsta  alexandrashipppp  ...  \
0               0    0            0                 0                 0  ...   
1               0    0            0                 0                 0  ...   
2               0    0            0                 0                 0  ...   
3               0    0            0                 0                 0  ...   
4               0    0            0                 0                 0  ...   
..            ...  ...          ...               ...               ...  ...   
160             0    0            0                 0                 0  ...   
161             0    0            0                 0                 1  ...   
162             0    0            0                 0                 0  ...   
163             0    0            0                 0                 0  ...   
164             0    0            0                 0                 0  ...   

     willpowerpacker  willsmith  wmag  woodyharrelson  wwe  \
0                  0          0     0               0    0   
1                  0          0     0               0    0   
2                  0          0     0               0    0   
3                  0          0     0               0    0   
4                  0          0     0               0    0   
..               ...        ...   ...             ...  ...   
160                0          0     0               0    0   
161                0          0     0               0    0   
162                0          0     0               0    0   
163                0          0     0               0    0   
164                0          0     0               1    0   

     yahooentertainment  zacefron  zaziebeetz  zendaya  zoeydeutch  
0                     0         0           0        0           0  
1                     0         0           0        0           0  
2                     0         0           0        0           0  
3                     0         0           0        0           0  
4                     0         0           0        0           0  
..                  ...       ...         ...      ...         ...  
160                   0         0           0        0           0  
161                   1         0           0        0           0  
162                   0         0           0        0           0  
163                   0         0           0        0           0  
164                   0         0           0        0           1  

[165 rows x 473 columns]

In [21]:
df = df.iloc[:, 1:]
df

20thcenturyfox  a24  accessonline  adamsandler  adamshankman  agt  \
0                 0    0             0            0             0    0   
1                 0    0             0            0             0    0   
2                 0    0             0            0             0    0   
3                 0    0             0            0             0    0   
4                 1    0             0            0             0    0   
..              ...  ...           ...          ...           ...  ...   
160               0    0             0            0             0    0   
161               1    0             0            0             0    0   
162               0    0             0            0             0    0   
163               0    0             0            0             0    0   
164               0    0             0            0             0    0   

     aldis_hodge  alecbaldwininsta  alexandrashipppp  alexbrown32  ...  \
0              0                 0                 0            0  ...   
1              0                 0                 0            0  ...   
2              0                 0                 0            0  ...   
3              0                 0                 0            0  ...   
4              0                 0                 0            0  ...   
..           ...               ...               ...          ...  ...   
160            0                 0                 0            0  ...   
161            0                 0                 1            0  ...   
162            0                 0                 0            0  ...   
163            0                 0                 0            0  ...   
164            0                 0                 0            0  ...   

     willpowerpacker  willsmith  wmag  woodyharrelson  wwe  \
0                  0          0     0               0    0   
1                  0          0     0               0    0   
2                  0          0     0               0    0   
3                  0          0     0               0    0   
4                  0          0     0               0    0   
..               ...        ...   ...             ...  ...   
160                0          0     0               0    0   
161                0          0     0               0    0   
162                0          0     0               0    0   
163                0          0     0               0    0   
164                0          0     0               1    0   

     yahooentertainment  zacefron  zaziebeetz  zendaya  zoeydeutch  
0                     0         0           0        0           0  
1                     0         0           0        0           0  
2                     0         0           0        0           0  
3                     0         0           0        0           0  
4                     0         0           0        0           0  
..                  ...       ...         ...      ...         ...  
160                   0         0           0        0           0  
161                   1         0           0        0           0  
162                   0         0           0        0           0  
163                   0         0           0        0           0  
164                   0         0           0        0           1  

[165 rows x 472 columns]

In [22]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 472) [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]


In [23]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Social

In [2]:
PATH = '../Social/social_norm.csv'
SAVE_NAME = 'social'

In [3]:
df = pd.read_csv(PATH)
df

Account     tconst  averageRating  numVotes          Uid  \
0        21bridgesmovie  tt8688634            6.6     18694   8600709558   
1          47metersdown  tt7329656            5.0     12683   4773990401   
2    abeautifuldaymovie  tt3224458            7.4     29979   9457986739   
3       abominablemovie  tt6324278            7.0     18487   8751027688   
4          adastramovie  tt2935510            6.6    147914   8014594288   
..                  ...        ...            ...       ...          ...   
160    wrinklestheclown  tt9097270            4.7       537  16149244607   
161          xmenmovies  tt6565702            5.8    125765    401420930   
162          yardiefilm  tt5862902            5.8      2248   6552487116   
163      yesterdaymovie  tt8079248            6.9     79700  10390112691   
164          zombieland  tt1560220            6.8     87731   9139732106   

     Posts  Followers     Likes  Comments  averageRating_norm  numVotes_norm  \
0       81      15595     73032      1468                0.66       0.026113   
1       61      38297    234154      5986                0.50       0.017533   
2      133      32213    245879      3323                0.74       0.042220   
3      134      19847    152470      2489                0.70       0.025817   
4      118      19262    349380      8189                0.66       0.210550   
..     ...        ...       ...       ...                 ...            ...   
160     72      19564    108787      3289                0.47       0.000197   
161   1333    1036371  12189097    115918                0.58       0.178936   
162     47       6574     25558      1436                0.58       0.002639   
163    118      45500    500137      8931                0.69       0.113187   
164    151      97918   1013914     11326                0.68       0.124650   

     Posts_norm  Followers_norm  Likes_norm  Comments_norm  
0      0.016297        0.001166    0.000189       0.000457  
1      0.010954        0.002924    0.000628       0.001993  
2      0.030190        0.002453    0.000660       0.001087  
3      0.030457        0.001495    0.000405       0.000804  
4      0.026182        0.001450    0.000942       0.002742  
..          ...             ...         ...            ...  
160    0.013893        0.001473    0.000286       0.001076  
161    0.350788        0.080235    0.033188       0.039364  
162    0.007213        0.000467    0.000060       0.000446  
163    0.026182        0.003482    0.001352       0.002994  
164    0.034999        0.007542    0.002751       0.003808  

[165 rows x 15 columns]

In [4]:
df = df.iloc[:, 9:]
df

averageRating_norm  numVotes_norm  Posts_norm  Followers_norm  \
0                  0.66       0.026113    0.016297        0.001166   
1                  0.50       0.017533    0.010954        0.002924   
2                  0.74       0.042220    0.030190        0.002453   
3                  0.70       0.025817    0.030457        0.001495   
4                  0.66       0.210550    0.026182        0.001450   
..                  ...            ...         ...             ...   
160                0.47       0.000197    0.013893        0.001473   
161                0.58       0.178936    0.350788        0.080235   
162                0.58       0.002639    0.007213        0.000467   
163                0.69       0.113187    0.026182        0.003482   
164                0.68       0.124650    0.034999        0.007542   

     Likes_norm  Comments_norm  
0      0.000189       0.000457  
1      0.000628       0.001993  
2      0.000660       0.001087  
3      0.000405       0.000804  
4      0.000942       0.002742  
..          ...            ...  
160    0.000286       0.001076  
161    0.033188       0.039364  
162    0.000060       0.000446  
163    0.001352       0.002994  
164    0.002751       0.003808  

[165 rows x 6 columns]

In [5]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 6) [[6.60000000e-01 2.61126605e-02 1.62970879e-02 1.16561411e-03
  1.88904463e-04 4.56889703e-04]
 [5.00000000e-01 1.75330922e-02 1.09537804e-02 2.92410503e-03
  6.27732371e-04 1.99277339e-03]
 [7.40000000e-01 4.22198687e-02 3.01896874e-02 2.45284000e-03
  6.59666292e-04 1.08749268e-03]
 [7.00000000e-01 2.58172071e-02 3.04568528e-02 1.49497290e-03
  4.05259842e-04 8.03976300e-04]
 [6.60000000e-01 2.10549829e-01 2.61822068e-02 1.44965896e-03
  9.41559064e-04 2.74167817e-03]
 [7.40000000e-01 1.79413032e-02 5.12957521e-02 4.58027164e-03
  1.42849621e-03 3.80639435e-03]
 [6.30000000e-01 1.84351530e-02 8.28212664e-03 1.52130921e-04
  3.75308684e-05 8.70266101e-05]
 [5.40000000e-01 3.44039120e-02 9.35078814e-03 1.77203011e-01
  6.56199044e-02 1.56080865e-01]
 [7.60000000e-01 9.11481007e-03 4.54181138e-03 1.33772964e-04
  1.97731571e-05 2.14167048e-05]
 [7.30000000e-01 2.74944406e-01 8.89660700e-02 1.00914544e-02
  5.07712031e-03 8.79852626e-03]
 [6.40000000e-01 7.46512365e-02 5.2631578

In [6]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

# Movie genre

In [14]:
PATH = '../genresMat.csv'
SAVE_NAME = 'movie_genre'

In [15]:
df = pd.read_csv(PATH)
df

movie  Action  Adventure  Animation  Biography  Comedy  \
0        21bridgesmovie       1          0          0          0       0   
1          47metersdown       0          1          0          0       0   
2    abeautifuldaymovie       0          0          0          1       0   
3       abominablemovie       0          1          1          0       1   
4          adastramovie       0          1          0          0       0   
..                  ...     ...        ...        ...        ...     ...   
160    wrinklestheclown       0          0          0          0       1   
161          xmenmovies       1          1          0          0       0   
162          yardiefilm       0          0          0          0       0   
163      yesterdaymovie       0          0          0          0       1   
164          zombieland       1          0          0          0       1   

     Crime  Documentary  Drama  Family  ...  History  Horror  Music  Mystery  \
0        1            0      1       0  ...        0       0      0        0   
1        0            0      1       0  ...        0       1      0        0   
2        0            0      1       0  ...        0       0      0        0   
3        0            0      0       0  ...        0       0      0        0   
4        0            0      1       0  ...        0       0      0        1   
..     ...          ...    ...     ...  ...      ...     ...    ...      ...   
160      0            1      0       0  ...        0       1      0        0   
161      0            0      0       0  ...        0       0      0        0   
162      1            0      1       0  ...        0       0      0        0   
163      0            0      0       0  ...        0       0      1        0   
164      0            0      0       0  ...        0       1      0        0   

     Romance  Sci-Fi  Sport  Thriller  War  Western  
0          0       0      0         0    0        0  
1          0       0      0         0    0        0  
2          0       0      0         0    0        0  
3          0       0      0         0    0        0  
4          0       0      0         0    0        0  
..       ...     ...    ...       ...  ...      ...  
160        0       0      0         0    0        0  
161        0       1      0         0    0        0  
162        0       0      0         0    0        0  
163        0       0      0         0    0        0  
164        0       0      0         0    0        0  

[165 rows x 21 columns]

In [16]:
df = df.iloc[:, 1:]
df

Action  Adventure  Animation  Biography  Comedy  Crime  Documentary  \
0         1          0          0          0       0      1            0   
1         0          1          0          0       0      0            0   
2         0          0          0          1       0      0            0   
3         0          1          1          0       1      0            0   
4         0          1          0          0       0      0            0   
..      ...        ...        ...        ...     ...    ...          ...   
160       0          0          0          0       1      0            1   
161       1          1          0          0       0      0            0   
162       0          0          0          0       0      1            0   
163       0          0          0          0       1      0            0   
164       1          0          0          0       1      0            0   

     Drama  Family  Fantasy  History  Horror  Music  Mystery  Romance  Sci-Fi  \
0        1       0        0        0       0      0        0        0       0   
1        1       0        0        0       1      0        0        0       0   
2        1       0        0        0       0      0        0        0       0   
3        0       0        0        0       0      0        0        0       0   
4        1       0        0        0       0      0        1        0       0   
..     ...     ...      ...      ...     ...    ...      ...      ...     ...   
160      0       0        0        0       1      0        0        0       0   
161      0       0        0        0       0      0        0        0       1   
162      1       0        0        0       0      0        0        0       0   
163      0       0        1        0       0      1        0        0       0   
164      0       0        0        0       1      0        0        0       0   

     Sport  Thriller  War  Western  
0        0         0    0        0  
1        0         0    0        0  
2        0         0    0        0  
3        0         0    0        0  
4        0         0    0        0  
..     ...       ...  ...      ...  
160      0         0    0        0  
161      0         0    0        0  
162      0         0    0        0  
163      0         0    0        0  
164      0         0    0        0  

[165 rows x 20 columns]

In [17]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 20) [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [18]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

# User preference

## User following

In [19]:
PATH = '../User/output/UserFollowingsMat.csv'
SAVE_NAME = 'user_followings'

In [20]:
df = pd.read_csv(PATH, header = None)
df

0               1             2                   3    \
0              NaN  21bridgesmovie  47metersdown  abeautifuldaymovie   
1     2.289300e+04               0             0                   1   
2     2.925001e+06               0             0                   0   
3     3.002253e+06               0             0                   0   
4     3.328685e+06               0             0                   0   
...            ...             ...           ...                 ...   
1578  1.768764e+10               0             0                   0   
1579  1.804532e+10               0             1                   1   
1580  1.888740e+10               0             0                   1   
1581  2.202644e+10               0             0                   1   
1582  2.433737e+10               0             0                   0   

                  4             5                  6               7    \
0     abominablemovie  adastramovie  adogsjourneymovie  aftermathmovie   
1                   0             0                  0               0   
2                   1             0                  0               0   
3                   0             0                  0               0   
4                   0             0                  1               0   
...               ...           ...                ...             ...   
1578                1             0                  0               0   
1579                0             0                  0               0   
1580                0             1                  0               0   
1581                0             0                  0               0   
1582                0             0                  0               0   

             8                9    ...                 156      157  \
0     aftermovie  ahiddenlifefilm  ...  underthesilverlake  usmovie   
1              0                0  ...                   0        0   
2              0                0  ...                   0        0   
3              0                0  ...                   0        0   
4              0                0  ...                   0        0   
...          ...              ...  ...                 ...      ...   
1578           0                0  ...                   0        0   
1579           0                0  ...                   0        0   
1580           0                0  ...                   0        0   
1581           0                0  ...                   0        0   
1582           0                0  ...                   0        0   

             158          159              160               161         162  \
0     wavesmovie  whatmenwant  wonderparkmovie  wrinklestheclown  xmenmovies   
1              0            0                0                 0           0   
2              0            0                0                 0           0   
3              0            0                0                 0           0   
4              0            0                0                 0           1   
...          ...          ...              ...               ...         ...   
1578           0            0                0                 0           0   
1579           0            0                0                 0           0   
1580           0            0                0                 0           0   
1581           0            0                0                 0           0   
1582           0            0                0                 0           0   

             163             164         165  
0     yardiefilm  yesterdaymovie  zombieland  
1              0               0           0  
2              0               1           0  
3              0               0           0  
4              0               0           0  
...          ...             ...         ...  
1578           0               0           0  
1579           0               0           0  
1580           0        

In [21]:
df = df.loc[1:, 1:]
df

1   2   3   4   5   6   7   8   9   10   ... 156 157 158 159 160 161 162  \
1      0   0   1   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2      0   0   0   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4      0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   1   
5      0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
1578   0   0   0   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1579   0   1   1   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1580   0   0   1   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1581   0   0   1   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1582   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

     163 164 165  
1      0   0   0  
2      0   1   0  
3      0   0   0  
4      0   0   0  
5      0   0   0  
...   ..  ..  ..  
1578   0   0   0  
1579   0   0   0  
1580   0   0   0  
1581   0   0   0  
1582   0   0   0  

[1582 rows x 165 columns]

In [22]:
npy = df.to_numpy().astype(int)
print(npy.shape, npy)

(1582, 165) [[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [23]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

## User genre

In [24]:
SAVE_NAME = 'user_genre'

In [25]:
user_followings = np.load('./npy/user_followings.npy')
movie_genre = np.load('./npy/movie_genre.npy')

In [26]:
user_followings = user_followings.astype(int)
movie_genre = movie_genre.astype(int)

In [27]:
user_genre = user_followings.dot(movie_genre)

In [28]:
print(user_genre.shape)

(1582, 20)


In [29]:
df = pd.DataFrame(user_genre)
df

0  1  2  3  4  5  6   7  8  9  10  11  12  13  14  15  16  17  18  19
0     2  1  0  4  2  1  0   9  0  0   2   0   0   0   1   1   0   1   0   0
1     4  8  4  0  9  1  0   2  1  4   0   0   1   0   2   1   0   0   0   0
2     2  2  2  0  4  2  0   5  0  1   0   2   0   1   1   0   1   1   0   0
3     2  5  2  1  7  1  0   6  0  0   0   0   0   0   1   2   0   1   0   0
4     3  2  0  0  3  1  0   1  0  2   0   7   0   3   0   2   0   3   0   0
...  .. .. .. .. .. .. ..  .. .. ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
1577  4  3  2  0  5  1  0   5  0  1   0   1   0   0   2   2   0   1   0   0
1578  4  5  2  1  3  2  0   6  0  1   0   3   0   1   0   2   0   1   0   0
1579  5  3  0  6  4  5  0  19  0  0   3   1   0   1   1   2   0   1   1   0
1580  2  2  0  3  3  1  0   7  0  0   1   1   0   0   0   1   0   0   1   0
1581  3  2  0  2  4  4  0   9  0  3   0   3   0   0   0   0   0   1   1   0

[1582 rows x 20 columns]

In [30]:
npy = df.to_numpy()
print(npy.shape, npy)

(1582, 20) [[2 1 0 ... 1 0 0]
 [4 8 4 ... 0 0 0]
 [2 2 2 ... 1 0 0]
 ...
 [5 3 0 ... 1 1 0]
 [2 2 0 ... 0 1 0]
 [3 2 0 ... 1 1 0]]


In [31]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

In [33]:
columns = read_json('../orderedListGenres.json')
print(len(columns), columns)
users = read_json('../orderedListUsers.json')
print(len(users), users)

20 ['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'Western']
1582 [22893, 2925001, 3002253, 3328685, 3920740, 6636654, 8952912, 9099063, 9305486, 10063561, 10315987, 12478419, 13446014, 13666697, 13929372, 15880020, 16577852, 20831536, 22390259, 22665807, 22972222, 23717132, 23741001, 24065858, 26031390, 26854659, 27641435, 28590046, 29436977, 30493895, 31002864, 31114801, 31491449, 32658266, 32863772, 34041315, 34072645, 37143636, 39075473, 39601435, 41045275, 43595803, 43667376, 44976539, 47271021, 48608470, 48704477, 49566480, 49721995, 50542000, 52314618, 53617153, 53778071, 55331126, 56034679, 104814625, 104835009, 143589068, 145442080, 145975918, 174618452, 174651842, 174960663, 175070187, 175143504, 175421228, 176349796, 176704140, 177802125, 179236119, 180651742, 180778157, 181064792, 182183648, 182366141, 183912134, 184377

In [34]:
df.columns = columns
df.index = users
df

Action  Adventure  Animation  Biography  Comedy  Crime  \
22893             2          1          0          4       2      1   
2925001           4          8          4          0       9      1   
3002253           2          2          2          0       4      2   
3328685           2          5          2          1       7      1   
3920740           3          2          0          0       3      1   
...             ...        ...        ...        ...     ...    ...   
17687638563       4          3          2          0       5      1   
18045323488       4          5          2          1       3      2   
18887395150       5          3          0          6       4      5   
22026438960       2          2          0          3       3      1   
24337372261       3          2          0          2       4      4   

             Documentary  Drama  Family  Fantasy  History  Horror  Music  \
22893                  0      9       0        0        2       0      0   
2925001                0      2       1        4        0       0      1   
3002253                0      5       0        1        0       2      0   
3328685                0      6       0        0        0       0      0   
3920740                0      1       0        2        0       7      0   
...                  ...    ...     ...      ...      ...     ...    ...   
17687638563            0      5       0        1        0       1      0   
18045323488            0      6       0        1        0       3      0   
18887395150            0     19       0        0        3       1      0   
22026438960            0      7       0        0        1       1      0   
24337372261            0      9       0        3        0       3      0   

             Mystery  Romance  Sci-Fi  Sport  Thriller  War  Western  
22893              0        1       1      0         1    0        0  
2925001            0        2       1      0         0    0        0  
3002253            1        1       0      1         1    0        0  
3328685            0        1       2      0         1    0        0  
3920740            3        0       2      0         3    0        0  
...              ...      ...     ...    ...       ...  ...      ...  
17687638563        0        2       2      0         1    0        0  
18045323488        1        0       2      0         1    0        0  
18887395150        1        1       2      0         1    1        0  
22026438960        0        0       1      0         0    1        0  
24337372261        0        0       0      0         1    1        0  

[1582 rows x 20 columns]

In [35]:
df.to_csv('../User/output/UserGenreMat.csv')

# Merge all features

In [7]:
text_npy = np.load('./npy/text.npy')
poster_npy = np.load('./npy/poster.npy')
IGimg_npy = np.load('./npy/IGimg.npy')
video_npy = np.load('./npy/video.npy')
follow_npy = np.load('./npy/follow.npy')
social_npy = np.load('./npy/social.npy')

print('Text:', text_npy.shape)
print('Poster:', poster_npy.shape)
print('IGimg:', IGimg_npy.shape)
print('Video:', video_npy.shape)
print('Follow:', follow_npy.shape)
print('Social:', social_npy.shape)

Text: (165, 300)
Poster: (165, 2048)
IGimg: (165, 2048)
Video: (165, 8)
Follow: (165, 472)
Social: (165, 6)


In [8]:
npys = [poster_npy, IGimg_npy, video_npy, follow_npy, social_npy]

In [9]:
tmp = text_npy

for npy in npys:
    tmp = np.hstack([tmp, npy])
    
print(tmp.shape)

(165, 4882)


In [10]:
SAVE_NAME = 'all_4882'

In [11]:
np.save('./npy/' + SAVE_NAME + '.npy', tmp)